package proyecto.comercioapp;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import proyecto.db.DBMediator;

public class EditFactura extends javax.swing.JDialog {

    private FacturasEditView parent;
    private int facturaID;
    private SimpleDateFormat formatoFecha;
    
    public EditFactura(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public EditFactura(FacturasEditView parent, boolean modal, int facturaID){
        super(parent, modal);
        this.parent = parent;
        initComponents();
        this.formatoFecha =  new SimpleDateFormat("yyyy-MM-dd");
        this.facturaID = facturaID;
        this.setTitle("Editando Factura #" + facturaID);
        cargarDatosFactura();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        facturasPanel = new javax.swing.JPanel();
        facturaIDLabel = new javax.swing.JLabel();
        fechaLabel = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        envioLabel = new javax.swing.JLabel();
        estadoLabel = new javax.swing.JLabel();
        estadoComboBox = new javax.swing.JComboBox<>();
        acceptButton = new javax.swing.JButton();
        facturaDateChooser = new com.toedter.calendar.JDateChooser();
        productosLabel = new javax.swing.JLabel();
        costoTextField = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        facturasPanel.setBackground(new java.awt.Color(153, 204, 255));

        facturaIDLabel.setForeground(new java.awt.Color(0, 0, 0));
        facturaIDLabel.setText("FacturaID: ");

        fechaLabel.setForeground(new java.awt.Color(0, 0, 0));
        fechaLabel.setText("Fecha:");

        totalLabel.setForeground(new java.awt.Color(0, 0, 0));
        totalLabel.setText("Total:");

        envioLabel.setForeground(new java.awt.Color(0, 0, 0));
        envioLabel.setText("Costo de Envío: ");

        estadoLabel.setForeground(new java.awt.Color(0, 0, 0));
        estadoLabel.setText("Estado:");

        estadoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "En Preparación", "Enviado", "Entregado" }));

        acceptButton.setText("Aceptar");
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });

        facturaDateChooser.setMaxSelectableDate(new Date());

        productosLabel.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        productosLabel.setForeground(new java.awt.Color(0, 0, 0));
        productosLabel.setText("Editar Factura");

        javax.swing.GroupLayout facturasPanelLayout = new javax.swing.GroupLayout(facturasPanel);
        facturasPanel.setLayout(facturasPanelLayout);
        facturasPanelLayout.setHorizontalGroup(
            facturasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facturasPanelLayout.createSequentialGroup()
                .addGroup(facturasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(facturasPanelLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(productosLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(facturasPanelLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(facturasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(facturasPanelLayout.createSequentialGroup()
                                .addComponent(fechaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(facturaDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(facturasPanelLayout.createSequentialGroup()
                                .addComponent(envioLabel)
                                .addGap(2, 2, 2)
                                .addComponent(costoTextField))
                            .addGroup(facturasPanelLayout.createSequentialGroup()
                                .addComponent(estadoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(estadoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(facturaIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(facturasPanelLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(acceptButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        facturasPanelLayout.setVerticalGroup(
            facturasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facturasPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(productosLabel)
                .addGap(27, 27, 27)
                .addComponent(facturaIDLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(facturasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaLabel)
                    .addComponent(facturaDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(facturasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(envioLabel)
                    .addComponent(costoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(facturasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estadoLabel)
                    .addComponent(estadoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(acceptButton)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(facturasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(facturasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        try{
            String fechaFactura = formatoFecha.format(facturaDateChooser.getDate());
            Float costoEnvio = Float.valueOf(costoTextField.getText());
            String estado = (String) estadoComboBox.getSelectedItem();
            
            int res = DBMediator.updateFactura(facturaID, fechaFactura, costoEnvio, estado);
            switch(res){
                case 0->{
                     JOptionPane.showMessageDialog(this, "Se ha actualizado exitosamente la factura.", "Notificación", JOptionPane.INFORMATION_MESSAGE);
                     parent.resetearPagina();
                     parent.actualizarPanelesFacturas(0); // Llama al método para actualizar la lista
                    this.dispose();                   
                }case -1 ->{
                    JOptionPane.showMessageDialog(this, "No se ha encontrado la factura por su ID.", "Advertencia", JOptionPane.WARNING_MESSAGE);
                }default ->{
                    JOptionPane.showMessageDialog(this, "Verifique llenar todos los espacios correctamente.", "Advertencia", JOptionPane.WARNING_MESSAGE);                    
                }
            }
       }catch(NumberFormatException nfe){
              JOptionPane.showMessageDialog(this, "Verifique que el costo ingresado sea un número cualquiera.", "Advertencia", JOptionPane.WARNING_MESSAGE);           
       }catch (NullPointerException npe){
              JOptionPane.showMessageDialog(this, "Verifique haber ingresado una fecha antes de continuar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
              return;              
       }catch (Exception e){
                e.printStackTrace();
               JOptionPane.showMessageDialog(this, "Ha ocurrido un error, intente de nuevo más tarde.", "Advertencia", JOptionPane.ERROR_MESSAGE);
              return;                
       }   
    }//GEN-LAST:event_acceptButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditFactura dialog = new EditFactura(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private void cargarDatosFactura(){
        List <Object> facturaInfo = DBMediator.getFacturaPorID(facturaID);
        facturaIDLabel.setText("Factura ID: " + facturaID);
        facturaDateChooser.setDate((Date) facturaInfo.get(0));
        totalLabel.setText("Total: £ "+ Float.toString((Float) facturaInfo.get(1)));
        costoTextField.setText(Float.toString((Float) facturaInfo.get(2)));
        estadoComboBox.setSelectedItem(facturaInfo.get(3));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JTextField costoTextField;
    private javax.swing.JLabel envioLabel;
    private javax.swing.JComboBox<String> estadoComboBox;
    private javax.swing.JLabel estadoLabel;
    private com.toedter.calendar.JDateChooser facturaDateChooser;
    private javax.swing.JLabel facturaIDLabel;
    private javax.swing.JPanel facturasPanel;
    private javax.swing.JLabel fechaLabel;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel productosLabel;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
