package proyecto.comercioapp;

import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.SwingWorker;
import proyecto.db.DBMediator;

public class HomeView extends javax.swing.JFrame {

    private int usuarioID;
    private int pagina;
    private String descuentoURL;
    private Map<Integer, JButton> botonesProductos;
    private List<List<Object>> productosPagina;
    
    public HomeView() {
        initComponents();
    }
    
    public HomeView(int usuarioID){
        initComponents();
        this.setLayout(null);
        this.usuarioID = usuarioID;
        this.descuentoURL = "https://i.ibb.co/4tMXLwq/descuento-img.png";
        this.pagina = 0;
        this.botonesProductos = new TreeMap<>();
        this.productosPagina = new ArrayList<>();
        crearBotonesProductos();
        actualizarBotones(pagina);
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuMomentaneo = new javax.swing.JPopupMenu();
        usuarioIcon = new javax.swing.JButton();
        anteriorButton = new javax.swing.JButton();
        siguienteButton = new javax.swing.JButton();
        shopIcon = new javax.swing.JButton();

        JMenuItem directionOption = new JMenuItem("Registrar Dirección");
        JMenuItem payOption = new JMenuItem("Agregar método de pago");
        JMenuItem logoutOption = new JMenuItem("Cerrar Sesión");

        // Agregar los elementos al menú emergente
        menuMomentaneo.add(directionOption);
        menuMomentaneo.add(payOption);
        menuMomentaneo.add(logoutOption);

        // Registrar la funcionalidad del click.
        directionOption.addActionListener(e -> {
            this.dispose();
            DirectionMenu directionMenu = new DirectionMenu(usuarioID);
            directionMenu.setVisible(true);
        });

        payOption.addActionListener(e -> {
            this.dispose();
            PayMethodMenu payMenu = new PayMethodMenu(usuarioID);
            payMenu.setVisible(true);
        });

        logoutOption.addActionListener(e -> {
            this.dispose();
            LoginView login = new LoginView();
            login.setVisible(true);
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Los Patitos Market");
        setResizable(false);

        try {
            URL urlUserIcon = new URL("https://i.ibb.co/QHRjgGg/icon-user.png");
            ImageIcon userIcon = new ImageIcon(urlUserIcon);
            usuarioIcon.setIcon(userIcon);

            // Agregar texto debajo del ícono y usar HTML para formatearlo en negrita
            usuarioIcon.setText("<html><center><b>Usuario</b></center></html>");

            // Configurar la posición del texto y el ícono
            usuarioIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            usuarioIcon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

            // Hacer el fondo transparente y quitar el borde
            usuarioIcon.setContentAreaFilled(false); // Hace que el fondo sea transparente
            usuarioIcon.setBorderPainted(false); // Quita el borde
            usuarioIcon.setFocusPainted(false); // Quita el borde de enfoque al hacer clic
        }catch(Exception e){
            usuarioIcon.setText("No se ha encontrado la imagen.");
        }
        usuarioIcon.setPreferredSize(new java.awt.Dimension(64, 64));
        usuarioIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioIconActionPerformed(evt);
            }
        });

        anteriorButton.setText("Página Anterior");
        anteriorButton.setPreferredSize(new java.awt.Dimension(120, 25));
        anteriorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorButtonActionPerformed(evt);
            }
        });

        siguienteButton.setText("Siguiente Página");
        siguienteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteButtonActionPerformed(evt);
            }
        });

        try {
            URL urlShopIcon = new URL("https://i.ibb.co/YTkGtvq/icon-shop.png");
            ImageIcon shop = new ImageIcon(urlShopIcon);
            shopIcon.setIcon(shop);

            // Agregar texto debajo del ícono y usar HTML para formatearlo en negrita
            shopIcon.setText("<html><center><b>Carrito</b></center></html>");

            // Configurar la posición del texto y el ícono
            shopIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            shopIcon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

            // Hacer el fondo transparente y quitar el borde
            shopIcon.setContentAreaFilled(false); // Hace que el fondo sea transparente
            shopIcon.setBorderPainted(false); // Quita el borde
            shopIcon.setFocusPainted(false); // Quita el borde de enfoque al hacer clic
        }catch(Exception e){
            shopIcon.setText("No se ha encontrado la imagen.");
        }
        shopIcon.setPreferredSize(new java.awt.Dimension(64, 64));
        shopIcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shopIconActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(311, 311, 311)
                .addComponent(anteriorButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(siguienteButton)
                .addContainerGap(385, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(shopIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usuarioIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usuarioIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shopIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 371, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anteriorButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(siguienteButton))
                .addGap(95, 95, 95))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioIconActionPerformed
        // Mostrar el menú emergente al mismo nivel que el frame
        menuMomentaneo.show(usuarioIcon, -5, usuarioIcon.getHeight());
    }//GEN-LAST:event_usuarioIconActionPerformed

    private void siguienteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteButtonActionPerformed
        pagina += 1;
        actualizarBotones(pagina);
    }//GEN-LAST:event_siguienteButtonActionPerformed

    private void anteriorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorButtonActionPerformed
        pagina -= 1;
        actualizarBotones(pagina);
    }//GEN-LAST:event_anteriorButtonActionPerformed

    private void shopIconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shopIconActionPerformed
        verificarEstadoCarrito(usuarioID);
        verificarStockCarrito(usuarioID);
        this.dispose();
        CarritoView cv = new CarritoView (usuarioID);
        cv.setVisible(true);
    }//GEN-LAST:event_shopIconActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeView().setVisible(true);
            }
        });
    }

    private int  verificarEstadoCarrito(int usuarioID){
        int resEstado = DBMediator.verificarEstadoCarrito(usuarioID);
        switch(resEstado) {
           case 0 -> {
               JOptionPane.showMessageDialog(this,
                       "Se han detectado cambios recientes en los precios o descuentos de algunos productos en su carrito.",
                       "Notificación",
                       JOptionPane.INFORMATION_MESSAGE);
                       return resEstado;
           }case 1->{
               return resEstado;
           }default ->{
                   JOptionPane.showMessageDialog(this,
                           "Ha ocurrido un error al cargar el carrito, intente de nuevo más tarde.",
                           "Advertencia",
                           JOptionPane.WARNING_MESSAGE);
                   return resEstado;
               }                    
         }       
    }
   
    private int verificarStockCarrito(int usuarioID){
        int resBorrado = DBMediator.verificarBorradoSinStock(usuarioID);
        switch(resBorrado) {
           case 0 -> {
               JOptionPane.showMessageDialog(this,
                       "Algunos productos han sido eliminados del carrito debido a su falta de stock.",
                       "Notificación",
                       JOptionPane.INFORMATION_MESSAGE);
               return resBorrado;
            }case 1->{
                return resBorrado;
           }default ->{
                   JOptionPane.showMessageDialog(this,
                           "Ha ocurrido un error al cargar el carrito, intente de nuevo más tarde.",
                           "Advertencia",
                           JOptionPane.WARNING_MESSAGE);
                   return resBorrado;
               }                    
         }       
    }
    
    private void crearBotonesProductos() {
        int xInicial = 80; // Posición inicial x
        int yInicial = 120; // Posición inicial y
        int anchoBoton = 150;
        int altoBoton = 150;
        int espacioEntreBotones = 10;

        // Crear 10 botones
        for (int  i = 0; i < 10; i++) {
            int botonPosition = i; // Variable temporal para capturar el valor de i
            JButton boton = new JButton("Botón " + (i + 1));
            boton.setBounds(xInicial, yInicial, anchoBoton, altoBoton);
            boton.setVisible(true); // Todos los botones visibles por defecto
            boton.addActionListener(e -> {showProductoInfo(botonPosition);});
            // Agregar el botón al mapa
            botonesProductos.put(i, boton);
            this.add(boton);
            
            // Actualizar la posición x para el siguiente botón
            xInicial += anchoBoton + espacioEntreBotones;

            // Si llegamos al quinto botón, bajar a la siguiente fila y resetear x
            if ((i + 1) % 5 == 0) {
                xInicial = 80; // Volver a la posición inicial en x
                yInicial += altoBoton + espacioEntreBotones; // Bajar en y
            }
            
        }   
    }
    

    private void actualizarBotones(int numPagina) {
        int index = 0;
        productosPagina = DBMediator.getProductosPorPagina(numPagina);
        int stillProducts = DBMediator.verificarProductosPorPagina(numPagina + 1);

        // Limpiar los íconos de descuento existentes de los botones
        for (JButton boton : botonesProductos.values()) {
            // Remover todos los componentes dentro del botón
            boton.removeAll();
            boton.revalidate();
            boton.repaint();
        }
        
        for (List<Object> producto : productosPagina) {
          JButton boton = botonesProductos.get(index);
          if (boton != null) {
              try {
                  // Cargar la imagen de forma asíncrona
                  cargarImagenEnBoton(boton, (String) producto.get(3));

                  // Configurar el texto con el nombre y el precio en negrita
                  String nombreProducto = (String) producto.get(1);
                  float precio = (Float) producto.get(2);
                  String texto = "<html><center>" + nombreProducto + "<br><b>£" + precio + "</b></center></html>";
                  boton.setText(texto);

                  // Configurar la posición del texto y la imagen
                  boton.setHorizontalTextPosition(SwingConstants.CENTER);
                  boton.setVerticalTextPosition(SwingConstants.BOTTOM);

                // Verificar si el producto tiene un descuento y agregar el ícono si es así
                if ("S".equals(producto.get(4))) {
                    URL urlDescuento = new URL(descuentoURL);
                    ImageIcon iconoDescuento = new ImageIcon(urlDescuento);
                    JLabel labelDescuento = new JLabel(iconoDescuento);
                    labelDescuento.setBounds(boton.getWidth() - iconoDescuento.getIconWidth() + 5, 0,
                                              iconoDescuento.getIconWidth(), iconoDescuento.getIconHeight());
                    boton.setLayout(null);
                    boton.add(labelDescuento);
                }
                
                  boton.setVisible(true);

              } catch (Exception e) {
                  System.out.println("Error al cargar la imagen: " + e.getMessage());
                  boton.setText("Error en imagen");
              }
              index++;
          }
      }
        // Ocultar los botones que no tienen datos
        for (int i = index; i < 10; i++) {
            JButton boton = botonesProductos.get(i);
            if (boton != null) {
                boton.setVisible(false);
            }
        }

        // Mostrar/ocultar botón "Anterior"
        anteriorButton.setVisible(pagina > 0);

        // Mostrar/ocultar botón "Siguiente" si hay menos de 10 productos
        siguienteButton.setVisible(stillProducts == 1);
    }

    private void showProductoInfo(int botonPosition){
        int productoID = (Integer) productosPagina.get(botonPosition).get(0); //Obtener el ID del producto del cual se toca el botón.
        ProductoCarrito pc = new ProductoCarrito(this, true, usuarioID, productoID);
        pc.setVisible(true);
    }

    private void cargarImagenEnBoton(JButton boton, String urlImagen) {
        SwingWorker<ImageIcon, Void> worker = new SwingWorker<>() {
            @Override
            protected ImageIcon doInBackground() throws Exception {
                try {
                    // Cargar la imagen en un hilo en segundo plano
                    URL url = new URL(urlImagen);
                    return new ImageIcon(url);
                } catch (Exception e) {
                    System.out.println("Error al cargar la imagen: " + e.getMessage());
                    return null;
                }
            }

            @Override
            protected void done() {
                try {
                    ImageIcon icono = get();
                    if (icono != null) {
                        boton.setIcon(icono);
                        boton.revalidate();
                        boton.repaint();
                    } else {
                        boton.setText("Imagen no disponible");
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                    boton.setText("Error en imagen");
                }
            }
        };

        // Ejecutar el worker
        worker.execute();
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anteriorButton;
    private javax.swing.JPopupMenu menuMomentaneo;
    private javax.swing.JButton shopIcon;
    private javax.swing.JButton siguienteButton;
    private javax.swing.JButton usuarioIcon;
    // End of variables declaration//GEN-END:variables
}
