package proyecto.comercioapp;

import java.awt.Color;
import java.net.URL;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import proyecto.db.DBMediator;


public class ProductoCarrito extends javax.swing.JDialog {
    private int usuarioID;
    private int productoID;
    private String productoNombre;
    private String productoDescripcion;
    private Float precio;
    private Float stock;
    private String categoria;
    private String marca;
    private Float calificacionPromedio;
    private String img;
    private int reviews;
    private Float descuento;
    private int productosContador;
    private String descuentoURL = "https://i.ibb.co/4tMXLwq/descuento-img.png";

    public ProductoCarrito(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
 
     public ProductoCarrito(java.awt.Frame parent, boolean modal, int usuarioID, int productoID) {
        super(parent, modal);
        llenarAtributos(DBMediator.getProductoInfo(productoID));
        initComponents();
        actualizarLabels();
        this.setTitle("Producto #" + productoID);
        this.usuarioID = usuarioID;
        this.productoID = productoID;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        extraLabel = new javax.swing.JLabel();
        infoGeneralLabel = new javax.swing.JLabel();
        lessButton = new javax.swing.JButton();
        cantidadTextLabel = new javax.swing.JLabel();
        moreButton = new javax.swing.JButton();
        cantidadLabel = new javax.swing.JLabel();
        iconLabel = new javax.swing.JLabel();
        addToCarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        extraLabel.setText("INFO EXTRA");

        infoGeneralLabel.setText("INFO GENERAL");

        lessButton.setText("-");
        lessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessButtonActionPerformed(evt);
            }
        });

        cantidadTextLabel.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        cantidadTextLabel.setText("Seleccione la cantidad:");

        moreButton.setText("+");
        moreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreButtonActionPerformed(evt);
            }
        });

        cantidadLabel.setText("1");

        iconLabel.setText(null);
        iconLabel.setLayout(null); // Usar un layout absoluto para permitir la posición manual de los componentes

        try {
            // Convertir la URL del String a un objeto URL
            URL imageUrl = new URL(img);

            // Crear un ImageIcon a partir de la URL
            ImageIcon imageIcon = new ImageIcon(imageUrl);

            // Asignar la imagen al JLabel
            iconLabel.setIcon(imageIcon);

            // Alinear la imagen al centro
            iconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            iconLabel.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
            iconLabel.setBorder(BorderFactory.createLineBorder(Color.BLACK, 4)); // Borde negro de 4 píxeles de grosor

            // Verificar si "descuento" es distinto de 0
            if (descuento != 0) {
                // Crear un JLabel para la imagen de la etiqueta de descuento
                JLabel descuentoLabel = new JLabel();
                URL descuentoUrl = new URL(descuentoURL); // URL de la imagen de descuento
                ImageIcon descuentoIcon = new ImageIcon(descuentoUrl);

                descuentoLabel.setIcon(descuentoIcon);

                // Configurar un tamaño y posición fijos para probar
                int iconLabelWidth = 150; // Ajusta el tamaño de prueba del JLabel
                int iconLabelHeight = 150; // Ajusta el tamaño de prueba del JLabel
                iconLabel.setSize(iconLabelWidth, iconLabelHeight); // Asegurarte de que tenga un tamaño fijo

                // Posicionar el label de descuento en la esquina superior derecha
                descuentoLabel.setBounds(iconLabelWidth - descuentoIcon.getIconWidth() + 3, 5, descuentoIcon.getIconWidth(), descuentoIcon.getIconHeight());

                // Añadir el label de descuento al iconLabel
                iconLabel.add(descuentoLabel);
                descuentoLabel.setVisible(true);
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

        addToCarButton.setText("Agregar al Carrito");
        addToCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(iconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoGeneralLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lessButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantidadLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moreButton))
                    .addComponent(cantidadTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(extraLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(addToCarButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(infoGeneralLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantidadTextLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lessButton)
                            .addComponent(cantidadLabel)
                            .addComponent(moreButton)))
                    .addComponent(iconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(extraLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 77, Short.MAX_VALUE)
                        .addComponent(addToCarButton)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void moreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreButtonActionPerformed
        if (productosContador < stock){
            productosContador += 1;
            cantidadLabel.setText(Integer.toString(productosContador));
        }
    }//GEN-LAST:event_moreButtonActionPerformed

    private void lessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessButtonActionPerformed
       if(productosContador > 1){
           productosContador -= 1;
           cantidadLabel.setText(Integer.toString(productosContador));
       }
    }//GEN-LAST:event_lessButtonActionPerformed

    private void addToCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCarButtonActionPerformed
        int res = DBMediator.UpsertCarritoProducto(usuarioID, productoID, productoNombre, productosContador, precio);
        switch (res) {
            case 0 -> {
                JOptionPane.showMessageDialog(this, "Se ha actualizado el carrito con " + productosContador + " existencias del producto.", "Notificación", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
            case 1 -> {
                JOptionPane.showMessageDialog(this, "Se ha agregado " + productosContador + " existencias del producto al carrito exitosamente.",
                        "Notificación", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }default ->{
                JOptionPane.showMessageDialog(this, "Ha ocurrido un error, intente de nuevo porfavor.", "Advertencia", JOptionPane.ERROR_MESSAGE);
                return;                
            }
        }
    }//GEN-LAST:event_addToCarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductoCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductoCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductoCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductoCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProductoCarrito dialog = new ProductoCarrito(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private void llenarAtributos(List<Object> productoInfo){
        productosContador = 1;
        productoNombre = (String) productoInfo.get(0);
        productoDescripcion = (String) productoInfo.get(1);
        precio = (Float) productoInfo.get(2);
        stock = (Float) productoInfo.get(3);
        categoria = (String) productoInfo.get(4);
        marca = (String) productoInfo.get(5);
        calificacionPromedio = (Float) productoInfo.get(6);
        img = (String) productoInfo.get(7);
        reviews = (Integer) productoInfo.get(8);
        descuento = (Float) productoInfo.get(9);
        System.out.println("DESCUENTO: " + descuento);
    }
    
private void actualizarLabels() {
    String contenidoExtra = "<html>"
            + "<b>Descripción:</b> " + productoDescripcion + "<br>"
            + "<b>Marca:</b> " + marca + "<br>"
            + "<b>Categoría:</b> " + categoria
            + "</html>";
    
    String contenidoInfo = "<html>"
            + "<b>Nombre:</b> " + productoNombre + "<br>"
            + "<b>Precio Unitario:</b> £" + precio + "<br>";
    
    if (descuento > 0){
        float dineroAhorrado = descuento/100 * precio;
        contenidoInfo += "<b>Descuento Aplicado:</b> £ -" + dineroAhorrado + "<br>";
        contenidoInfo += "<b>Precio Final:</b> £ " + (precio - dineroAhorrado) + "<br>";
    }else{
        contenidoInfo += "<b>Precio Final:</b> £ " + (precio) + "<br>";
    }
    
    
    if (reviews > 0) {
        contenidoInfo += "<b>Calificación Promedio:</b> " + calificacionPromedio + " ✩<br>";
    }
    contenidoInfo += "</html>";  // Cerrar la etiqueta HTML solo al final
    
    extraLabel.setText(contenidoExtra);
    infoGeneralLabel.setText(contenidoInfo);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCarButton;
    private javax.swing.JLabel cantidadLabel;
    private javax.swing.JLabel cantidadTextLabel;
    private javax.swing.JLabel extraLabel;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JLabel infoGeneralLabel;
    private javax.swing.JButton lessButton;
    private javax.swing.JButton moreButton;
    // End of variables declaration//GEN-END:variables
}
